name: Build and Deploy to GCS (Staging)

on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Upload to GCS with no-cache headers
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          bucket: ${{ secrets.GCP_BUCKET_NAME }}
          parent: false
          headers: |
            content-type: 'application/javascript'
            cache-control: 'private, max-age=0, no-transform'
