name: Build and Deploy to GCS (Staging)

on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Upload to GCS with Cache-Control headers
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: ${{ secrets.GCP_BUCKET_NAME }}
          parent: false
          overwrite: true
          gzip: false
          headers: |
            cache-control=public,max-age=0,must-revalidate

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Cache-Control headers with gsutil (fallback)
        run: |
          gsutil -m setmeta -h "Cache-Control:public,max-age=0,must-revalidate" gs://${{ secrets.GCP_BUCKET_NAME }}/**/*
